kind: Deployment
apiVersion: apps/v1
metadata:
  name: greeter-deployment
  namespace: greeter
  labels:
    app: greeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: "teymurgahramanov/greeter:v2"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m