kind: Namespace
apiVersion: v1
metadata:
  name: greeter
  labels:
    name: greeter
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: greeter-deployment
  namespace: greeter
  labels:
    app: greeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: "teymurgahramanov/greeter:latest"
        resources:
          requests:
            cpu: 10m
---
kind: Service
apiVersion: v1
metadata:
  name: greeter-service
  namespace: greeter
spec:
  selector:
    app: greeter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort