kind: Service
apiVersion: v1
metadata:
  name: greeter-service
  namespace: greeter
spec:
  selector:
    app: greeter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort